### ISSUE TITLE
Undefined class constant 'MYSQL_ATTR_INIT_COMMAND'

### ISSUE THREAD

**Issue by Namchee** [ftis-admin/pinjam-ruang#3]
Hello, @chez14 ! Thanks for implementing the API

I was trying to access `/migrate` but it only gave me an error code 500. It said that the 'MYSQL_ATTR_INIT_COMMAND' class is undefined. I'm running it on PHP version 7.2.8 on Windows 10.

Any idea why?

**Comment by chez14** [comment]
Ahh i see, this requires you to enable `php_pdo_mysql` ([Reference](https://stackoverflow.com/a/6735730/4721245)).

I'll add it to the sysreq, thanks for reporting.
